// Self-host the brand fonts (privacy + perf + tighter CSP).
//
// ONE-TIME / ON-DEMAND generator — NOT part of the build or deploy.
// Run it when first self-hosting, or to add a weight / refresh the files:
//
//   node scripts/generate-fonts.mjs
//
// What it does: asks Google Fonts for the CSS (with a modern Chrome UA so we get
// .woff2), downloads the latin + latin-ext subset files into assets/fonts/, and
// writes assets/fonts/fonts.css with @font-face rules pointing at those local
// files. After running, the .woff2 files + fonts.css are committed static assets;
// the live site loads them from our own origin and never touches Google.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = join(HERE, '..', 'assets', 'fonts');

// Must mirror the families/weights the page actually uses (see index.html).
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Baloo+2:wght@500;600;700' +
  '&family=Plus+Jakarta+Sans:wght@400;500;600;700' +
  '&display=swap';

// A modern UA makes Google return woff2 (older/blank UAs get ttf/woff).
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Keep the page small: only Latin coverage (DE/EN content). Drop cyrillic/greek/etc.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function main() {
  await mkdir(FONT_DIR, { recursive: true });

  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

  // Google emits `/* subset */` immediately before each @font-face block.
  const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  const pick = (block, prop) => (block.match(new RegExp(prop + '\\s*:\\s*([^;]+);')) || [])[1]?.trim();

  const faces = [];
  let m;
  while ((m = blockRe.exec(css)) !== null) {
    const subset = m[1];
    if (!KEEP_SUBSETS.has(subset)) continue;
    const block = m[2];
    const family = pick(block, 'font-family').replace(/['"]/g, '');
    const weight = pick(block, 'font-weight');
    const unicodeRange = pick(block, 'unicode-range');
    const url = (pick(block, 'src').match(/url\(([^)]+)\)/) || [])[1];
    const file = `${slug(family)}-${weight}-${subset}.woff2`;

    process.stdout.write(`↓ ${file}\n`);
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(join(FONT_DIR, file), buf);

    faces.push({ family, weight, unicodeRange, file });
  }

  if (!faces.length) throw new Error('No @font-face blocks parsed — did Google change the CSS format?');

  const out = faces
    .map(
      (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/assets/fonts/${f.file}') format('woff2');
  unicode-range: ${f.unicodeRange};
}`
    )
    .join('\n\n');

  const header = `/* Generated by scripts/generate-fonts.mjs — do not edit by hand.\n   Self-hosted brand fonts (no Google Fonts runtime dependency). */\n\n`;
  await writeFile(join(FONT_DIR, 'fonts.css'), header + out + '\n');

  process.stdout.write(`\n✓ ${faces.length} files + fonts.css written to assets/fonts/\n`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
